# 使用する時はファイル名の先頭に.(ドット)をつけ「.gitlab-ci.yml」とし、レポジトリのルートに配置してください。
stages:
  - build
  - deploy

zip-build:
  image: 
    name: kramos/alpine-zip
    entrypoint: [""]
  stage: build
  script:
    - zip settings ./*
  artifacts:
    paths:
      - settings.zip
  only:
    - master
  tags:
    - cicd-dev

s3-deploy:
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  stage: deploy
  variables:
    BACKET: cicd-dev-test-app
  script:
    - aws s3 cp ./settings.zip s3://${BACKET}
  only:
    - master
  tags:
    - cicd-dev
